# Generated by Django 6.0.2 on 2026-02-26 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galeria', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fotografica',
            new_name='Fotografia',
        ),
    ]
